language: elixir
os:
  - linux
  #- osx
python:
  - 2.7
install:
  - pip install coveralls
elixir:
  - 1.3.2
otp_release:
  - 18.2
script:
  - MIX_ENV=test mix test --trace --cover
after_success:
  - MIX_ENV=test mix credo -a
  - coveralls

services:
  - redis-server
sudo: false
