language: elixir
os:
  - linux
  #- osx
elixir:
  - 1.4
  - 1.5
otp_release:
  - 19
  - 20
script:
  - MIX_ENV=test mix test --trace
after_success:
  - MIX_ENV=test mix credo -a
  - mix coveralls.travis
services:
  - redis-server
sudo: false
