language: elixir
elixir:
  - 1.2.4
  - 1.3.2
otp_release:
  - 18.2
script:
  - MIX_ENV=test mix test --no-start --trace --cover
  - MIX_ENV=test mix credo --strict
services:
  - redis-server
sudo: false
