language: elixir
os:
  - linux
  #- osx
elixir:
  - 1.3.2
otp_release:
  - 18.2
script:
  - MIX_ENV=test mix test --trace
after_success:
  - MIX_ENV=test mix credo -a
  - mix coveralls.travis
services:
  - redis-server
sudo: false
